author: byfan # 作者
description: byfan's blog
keyword: hexo-theme, vuejs
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment or uyan

comment: gitment

# gitment config
gitment_owner: SpiritQAQ
gitment_repo: SpiritQAQ.github.io
gitment_oauth_id: 0f87e490e00ee3fd87ef
gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  banner: ../css/images/seaside.png
  avatar: http://q2.qlogo.cn/headimg_dl?dst_uin=444042073&spec=100
  description: "絜矩之道"
  weibo_username: 2647674234
  twitter_username: tarik
  github_username: SpiritQAQ
  zhihu_username: fan-zheng-wo-bu-huang-ha
  douban_username: 

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
